import Root from '@/app/(main)/home/components/Root'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <Root>
      {children}
    </Root>
  );
}